/* eslint-disable */
/* tslint:disable */
/* auto-generated react proxies */
import { createReactComponent } from './react-component-lib';

import type { JSX } from '@gasco/core/components';

import { defineCustomElement as defineGascoAccordion } from '@gasco/core/components/gasco-accordion.js';
import { defineCustomElement as defineGascoAccordionGroup } from '@gasco/core/components/gasco-accordion-group.js';
import { defineCustomElement as defineGascoAutocomplete } from '@gasco/core/components/gasco-autocomplete.js';
import { defineCustomElement as defineGascoBackdrop } from '@gasco/core/components/gasco-backdrop.js';
import { defineCustomElement as defineGascoButton } from '@gasco/core/components/gasco-button.js';
import { defineCustomElement as defineGascoButtonIcon } from '@gasco/core/components/gasco-button-icon.js';
import { defineCustomElement as defineGascoCard } from '@gasco/core/components/gasco-card.js';
import { defineCustomElement as defineGascoCardContent } from '@gasco/core/components/gasco-card-content.js';
import { defineCustomElement as defineGascoCardHeader } from '@gasco/core/components/gasco-card-header.js';
import { defineCustomElement as defineGascoCardTitle } from '@gasco/core/components/gasco-card-title.js';
import { defineCustomElement as defineGascoCheckbox } from '@gasco/core/components/gasco-checkbox.js';
import { defineCustomElement as defineGascoChip } from '@gasco/core/components/gasco-chip.js';
import { defineCustomElement as defineGascoContent } from '@gasco/core/components/gasco-content.js';
import { defineCustomElement as defineGascoDatetime } from '@gasco/core/components/gasco-datetime.js';
import { defineCustomElement as defineGascoDialog } from '@gasco/core/components/gasco-dialog.js';
import { defineCustomElement as defineGascoDialogContent } from '@gasco/core/components/gasco-dialog-content.js';
import { defineCustomElement as defineGascoDialogFooter } from '@gasco/core/components/gasco-dialog-footer.js';
import { defineCustomElement as defineGascoDialogHeader } from '@gasco/core/components/gasco-dialog-header.js';
import { defineCustomElement as defineGascoDialogTitle } from '@gasco/core/components/gasco-dialog-title.js';
import { defineCustomElement as defineGascoDivider } from '@gasco/core/components/gasco-divider.js';
import { defineCustomElement as defineGascoInput } from '@gasco/core/components/gasco-input.js';
import { defineCustomElement as defineGascoInputCode } from '@gasco/core/components/gasco-input-code.js';
import { defineCustomElement as defineGascoItem } from '@gasco/core/components/gasco-item.js';
import { defineCustomElement as defineGascoLabel } from '@gasco/core/components/gasco-label.js';
import { defineCustomElement as defineGascoList } from '@gasco/core/components/gasco-list.js';
import { defineCustomElement as defineGascoListHeader } from '@gasco/core/components/gasco-list-header.js';
import { defineCustomElement as defineGascoMenu } from '@gasco/core/components/gasco-menu.js';
import { defineCustomElement as defineGascoModal } from '@gasco/core/components/gasco-modal.js';
import { defineCustomElement as defineGascoPaginator } from '@gasco/core/components/gasco-paginator.js';
import { defineCustomElement as defineGascoPickerColumnInternal } from '@gasco/core/components/gasco-picker-column-internal.js';
import { defineCustomElement as defineGascoPickerInternal } from '@gasco/core/components/gasco-picker-internal.js';
import { defineCustomElement as defineGascoPopover } from '@gasco/core/components/gasco-popover.js';
import { defineCustomElement as defineGascoProgress } from '@gasco/core/components/gasco-progress.js';
import { defineCustomElement as defineGascoRadio } from '@gasco/core/components/gasco-radio.js';
import { defineCustomElement as defineGascoRange } from '@gasco/core/components/gasco-range.js';
import { defineCustomElement as defineGascoTab } from '@gasco/core/components/gasco-tab.js';
import { defineCustomElement as defineGascoTabButton } from '@gasco/core/components/gasco-tab-button.js';
import { defineCustomElement as defineGascoToast } from '@gasco/core/components/gasco-toast.js';
import { defineCustomElement as defineGascoTooltip } from '@gasco/core/components/gasco-tooltip.js';
import { defineCustomElement as defineIonIcon } from '@gasco/core/components/ion-icon.js';

export const GascoAccordion = /*@__PURE__*/createReactComponent<JSX.GascoAccordion, HTMLGascoAccordionElement>('gasco-accordion', undefined, undefined, defineGascoAccordion);
export const GascoAccordionGroup = /*@__PURE__*/createReactComponent<JSX.GascoAccordionGroup, HTMLGascoAccordionGroupElement>('gasco-accordion-group', undefined, undefined, defineGascoAccordionGroup);
export const GascoAutocomplete = /*@__PURE__*/createReactComponent<JSX.GascoAutocomplete, HTMLGascoAutocompleteElement>('gasco-autocomplete', undefined, undefined, defineGascoAutocomplete);
export const GascoBackdrop = /*@__PURE__*/createReactComponent<JSX.GascoBackdrop, HTMLGascoBackdropElement>('gasco-backdrop', undefined, undefined, defineGascoBackdrop);
export const GascoButton = /*@__PURE__*/createReactComponent<JSX.GascoButton, HTMLGascoButtonElement>('gasco-button', undefined, undefined, defineGascoButton);
export const GascoButtonIcon = /*@__PURE__*/createReactComponent<JSX.GascoButtonIcon, HTMLGascoButtonIconElement>('gasco-button-icon', undefined, undefined, defineGascoButtonIcon);
export const GascoCard = /*@__PURE__*/createReactComponent<JSX.GascoCard, HTMLGascoCardElement>('gasco-card', undefined, undefined, defineGascoCard);
export const GascoCardContent = /*@__PURE__*/createReactComponent<JSX.GascoCardContent, HTMLGascoCardContentElement>('gasco-card-content', undefined, undefined, defineGascoCardContent);
export const GascoCardHeader = /*@__PURE__*/createReactComponent<JSX.GascoCardHeader, HTMLGascoCardHeaderElement>('gasco-card-header', undefined, undefined, defineGascoCardHeader);
export const GascoCardTitle = /*@__PURE__*/createReactComponent<JSX.GascoCardTitle, HTMLGascoCardTitleElement>('gasco-card-title', undefined, undefined, defineGascoCardTitle);
export const GascoCheckbox = /*@__PURE__*/createReactComponent<JSX.GascoCheckbox, HTMLGascoCheckboxElement>('gasco-checkbox', undefined, undefined, defineGascoCheckbox);
export const GascoChip = /*@__PURE__*/createReactComponent<JSX.GascoChip, HTMLGascoChipElement>('gasco-chip', undefined, undefined, defineGascoChip);
export const GascoContent = /*@__PURE__*/createReactComponent<JSX.GascoContent, HTMLGascoContentElement>('gasco-content', undefined, undefined, defineGascoContent);
export const GascoDatetime = /*@__PURE__*/createReactComponent<JSX.GascoDatetime, HTMLGascoDatetimeElement>('gasco-datetime', undefined, undefined, defineGascoDatetime);
export const GascoDialog = /*@__PURE__*/createReactComponent<JSX.GascoDialog, HTMLGascoDialogElement>('gasco-dialog', undefined, undefined, defineGascoDialog);
export const GascoDialogContent = /*@__PURE__*/createReactComponent<JSX.GascoDialogContent, HTMLGascoDialogContentElement>('gasco-dialog-content', undefined, undefined, defineGascoDialogContent);
export const GascoDialogFooter = /*@__PURE__*/createReactComponent<JSX.GascoDialogFooter, HTMLGascoDialogFooterElement>('gasco-dialog-footer', undefined, undefined, defineGascoDialogFooter);
export const GascoDialogHeader = /*@__PURE__*/createReactComponent<JSX.GascoDialogHeader, HTMLGascoDialogHeaderElement>('gasco-dialog-header', undefined, undefined, defineGascoDialogHeader);
export const GascoDialogTitle = /*@__PURE__*/createReactComponent<JSX.GascoDialogTitle, HTMLGascoDialogTitleElement>('gasco-dialog-title', undefined, undefined, defineGascoDialogTitle);
export const GascoDivider = /*@__PURE__*/createReactComponent<JSX.GascoDivider, HTMLGascoDividerElement>('gasco-divider', undefined, undefined, defineGascoDivider);
export const GascoInput = /*@__PURE__*/createReactComponent<JSX.GascoInput, HTMLGascoInputElement>('gasco-input', undefined, undefined, defineGascoInput);
export const GascoInputCode = /*@__PURE__*/createReactComponent<JSX.GascoInputCode, HTMLGascoInputCodeElement>('gasco-input-code', undefined, undefined, defineGascoInputCode);
export const GascoItem = /*@__PURE__*/createReactComponent<JSX.GascoItem, HTMLGascoItemElement>('gasco-item', undefined, undefined, defineGascoItem);
export const GascoLabel = /*@__PURE__*/createReactComponent<JSX.GascoLabel, HTMLGascoLabelElement>('gasco-label', undefined, undefined, defineGascoLabel);
export const GascoList = /*@__PURE__*/createReactComponent<JSX.GascoList, HTMLGascoListElement>('gasco-list', undefined, undefined, defineGascoList);
export const GascoListHeader = /*@__PURE__*/createReactComponent<JSX.GascoListHeader, HTMLGascoListHeaderElement>('gasco-list-header', undefined, undefined, defineGascoListHeader);
export const GascoMenu = /*@__PURE__*/createReactComponent<JSX.GascoMenu, HTMLGascoMenuElement>('gasco-menu', undefined, undefined, defineGascoMenu);
export const GascoModal = /*@__PURE__*/createReactComponent<JSX.GascoModal, HTMLGascoModalElement>('gasco-modal', undefined, undefined, defineGascoModal);
export const GascoPaginator = /*@__PURE__*/createReactComponent<JSX.GascoPaginator, HTMLGascoPaginatorElement>('gasco-paginator', undefined, undefined, defineGascoPaginator);
export const GascoPickerColumnInternal = /*@__PURE__*/createReactComponent<JSX.GascoPickerColumnInternal, HTMLGascoPickerColumnInternalElement>('gasco-picker-column-internal', undefined, undefined, defineGascoPickerColumnInternal);
export const GascoPickerInternal = /*@__PURE__*/createReactComponent<JSX.GascoPickerInternal, HTMLGascoPickerInternalElement>('gasco-picker-internal', undefined, undefined, defineGascoPickerInternal);
export const GascoPopover = /*@__PURE__*/createReactComponent<JSX.GascoPopover, HTMLGascoPopoverElement>('gasco-popover', undefined, undefined, defineGascoPopover);
export const GascoProgress = /*@__PURE__*/createReactComponent<JSX.GascoProgress, HTMLGascoProgressElement>('gasco-progress', undefined, undefined, defineGascoProgress);
export const GascoRadio = /*@__PURE__*/createReactComponent<JSX.GascoRadio, HTMLGascoRadioElement>('gasco-radio', undefined, undefined, defineGascoRadio);
export const GascoRange = /*@__PURE__*/createReactComponent<JSX.GascoRange, HTMLGascoRangeElement>('gasco-range', undefined, undefined, defineGascoRange);
export const GascoTab = /*@__PURE__*/createReactComponent<JSX.GascoTab, HTMLGascoTabElement>('gasco-tab', undefined, undefined, defineGascoTab);
export const GascoTabButton = /*@__PURE__*/createReactComponent<JSX.GascoTabButton, HTMLGascoTabButtonElement>('gasco-tab-button', undefined, undefined, defineGascoTabButton);
export const GascoToast = /*@__PURE__*/createReactComponent<JSX.GascoToast, HTMLGascoToastElement>('gasco-toast', undefined, undefined, defineGascoToast);
export const GascoTooltip = /*@__PURE__*/createReactComponent<JSX.GascoTooltip, HTMLGascoTooltipElement>('gasco-tooltip', undefined, undefined, defineGascoTooltip);
export const IonIcon = /*@__PURE__*/createReactComponent<JSX.IonIcon, HTMLIonIconElement>('ion-icon', undefined, undefined, defineIonIcon);
